# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Repository rules for downloading the Dart SDK.

This module provides repository rules similar to rules_go and rules_rust that
automatically download and configure the Dart SDK for hermetic builds.

The Dart SDK is downloaded from the official Google storage:
https://storage.googleapis.com/dart-archive/channels/stable/release/{version}/sdk/

Supported platforms:
- linux-x64, linux-arm64
- macos-x64, macos-arm64
- windows-x64
"""

# Dart SDK version to download
DART_VERSION = "3.7.0"

# Dart SDK download URLs by platform
_DART_SDK_URLS = {
    "linux-x64": "https://storage.googleapis.com/dart-archive/channels/stable/release/{version}/sdk/dartsdk-linux-x64-release.zip",
    "linux-arm64": "https://storage.googleapis.com/dart-archive/channels/stable/release/{version}/sdk/dartsdk-linux-arm64-release.zip",
    "macos-x64": "https://storage.googleapis.com/dart-archive/channels/stable/release/{version}/sdk/dartsdk-macos-x64-release.zip",
    "macos-arm64": "https://storage.googleapis.com/dart-archive/channels/stable/release/{version}/sdk/dartsdk-macos-arm64-release.zip",
    "windows-x64": "https://storage.googleapis.com/dart-archive/channels/stable/release/{version}/sdk/dartsdk-windows-x64-release.zip",
}

# SHA256 checksums for Dart SDK 3.7.0 (update these when changing version)
# To get checksums: curl -sL <url> | shasum -a 256
_DART_SDK_SHA256 = {
    "linux-x64": "",  # TODO(#505): Add checksums for Dart SDK verification
    "linux-arm64": "",
    "macos-x64": "",
    "macos-arm64": "",
    "windows-x64": "",
}

def _get_platform(repository_ctx):
    """Determines the current platform string."""
    os_name = repository_ctx.os.name.lower()
    arch = repository_ctx.os.arch

    if "mac" in os_name or "darwin" in os_name:
        os_key = "macos"
    elif "linux" in os_name:
        os_key = "linux"
    elif "win" in os_name:
        os_key = "windows"
    else:
        fail("Unsupported operating system: " + os_name)

    if arch == "aarch64" or arch == "arm64":
        arch_key = "arm64"
    elif arch == "amd64" or arch == "x86_64" or arch == "x64":
        arch_key = "x64"
    else:
        fail("Unsupported architecture: " + arch)

    return os_key + "-" + arch_key

def _dart_sdk_impl(repository_ctx):
    """Implementation of the dart_sdk repository rule."""
    version = repository_ctx.attr.version
    platform = _get_platform(repository_ctx)

    if platform not in _DART_SDK_URLS:
        fail("No Dart SDK available for platform: " + platform)

    url = _DART_SDK_URLS[platform].format(version = version)
    sha256 = _DART_SDK_SHA256.get(platform, "")

    # Download and extract the SDK
    repository_ctx.report_progress("Downloading Dart SDK {} for {}...".format(version, platform))

    # Download the SDK zip file
    if sha256:
        repository_ctx.download_and_extract(
            url = url,
            sha256 = sha256,
            stripPrefix = "dart-sdk",
        )
    else:
        # No checksum verification (for development/initial setup)
        repository_ctx.download_and_extract(
            url = url,
            stripPrefix = "dart-sdk",
        )

    # Create the BUILD.bazel file
    repository_ctx.file("BUILD.bazel", content = """
# Auto-generated by dart_sdk repository rule.
# Dart SDK version: {version}
# Platform: {platform}

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "sdk",
    srcs = glob(["**"]),
)

# Dart executable
exports_files(["bin/dart"])

# Toolchain targets
filegroup(
    name = "dart_bin",
    srcs = ["bin/dart"],
)

filegroup(
    name = "dart_libs",
    srcs = glob(["lib/**"]),
)
""".format(version = version, platform = platform))

    # Create a wrapper script that sets up the environment
    dart_ext = ".exe" if "windows" in platform else ""
    repository_ctx.file("dart_wrapper.sh", content = """#!/bin/bash
# Dart SDK wrapper script
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
exec "$SCRIPT_DIR/bin/dart{ext}" "$@"
""".format(ext = dart_ext), executable = True)

dart_sdk = repository_rule(
    implementation = _dart_sdk_impl,
    attrs = {
        "version": attr.string(
            default = DART_VERSION,
            doc = "The Dart SDK version to download.",
        ),
    },
    doc = """Downloads and configures the Dart SDK.

This repository rule downloads the Dart SDK from the official Google storage
and makes it available for use in Bazel builds.

Example:
    dart_sdk(name = "dart_sdk", version = "3.7.0")
""",
)

def dart_rules_dependencies():
    """Declares external dependencies for Dart rules.

    Call this function in your WORKSPACE or MODULE.bazel to set up the
    Dart SDK repository.
    """
    dart_sdk(name = "dart_sdk")

def dart_register_toolchains(version = DART_VERSION):
    """Registers Dart toolchains.

    Args:
        version: The Dart SDK version to use.
    """

    # Register the SDK repository
    dart_sdk(
        name = "dart_sdk",
        version = version,
    )
