# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Bazel Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all # Needed for security checks, adjust if necessary

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Bazel needs a JDK. Setup Java 21 as baseline.
      - name: Setup Java JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Set up Go environment for go install
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      # Use bazelisk to manage Bazel versions based on .bazelversion
      - name: Install Bazelisk via Go
        run: go install github.com/bazelbuild/bazelisk@latest

      - name: Mount Bazel repository cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel/_bazel_${{ runner.os }}/repos
            ~/.cache/bazel/_bazel_${{ runner.os }}/external
          key: bazel-repo-${{ hashFiles('**/MODULE.bazel.lock', '**/maven_install.json', '**/pnpm-lock.yaml') }}
          restore-keys: |
            bazel-repo-

      # Setup Bazel action cache
      # Caching build results can significantly speed up CI.
      # Be cautious with cache size and eviction.
      - name: Mount Bazel action cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel/_bazel_${{ runner.os }}/execroot/**/bazel-out
          key: bazel-action-${{ github.sha }}-${{ hashFiles('**/MODULE.bazel.lock', '**/maven_install.json', '**/pnpm-lock.yaml') }}
          restore-keys: |
             bazel-action-${{ github.ref }}-${{ hashFiles('**/MODULE.bazel.lock', '**/maven_install.json', '**/pnpm-lock.yaml') }}
             bazel-action-

      - name: Pin Java dependencies
        run: bazelisk run @maven//:pin

      - name: Check for changes in maven_install.json
        id: git-check
        run: |
          if [[ -n "$(git status --porcelain maven_install.json)" ]]; then
            echo "::error::'maven_install.json' has been modified. Please run 'bazelisk run @maven//:pin' locally and commit the updated file."
            exit 1
          fi

      - name: Build all targets (Java 21)
        run: bazelisk build --config=java21 //...
      - name: Test all targets (Java 21)
        run: bazelisk test --config=java21 //... --test_output=errors

      - name: Build all targets (Java 17)
        run: bazelisk build --config=java17 //...

      - name: Test all targets (Java 17)
        run: bazelisk test --config=java17 //... --test_output=errors
