# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Go build, tests and other checks

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22.x', '1.23.x', '1.24.x']
      fail-fast: false

    name: Go ${{ matrix.go-version }} Tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@main
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Check build
        run: go build -C go -v ./...

      - name: Run tests
        run: go test -C go -v ./...

      - name: Run vulncheck
        run: govulncheck -C go ./...
