# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Go tests and checks

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22.x', '1.23.x', '1.24.x']
      fail-fast: false

    name: Go ${{ matrix.go-version }} Tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@main
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -C go -v ./... || true # TODO: Skip failures temporarily
