# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Python Checks

on: pull_request

jobs:
  python-checks:
    runs-on: ubuntu-latest
    env:
      PATH: ${{ github.workspace }}/go/bin:${{ github.workspace }}/.cargo/bin:${{ github.workspace }}/.local/share/pnpm:${{ github.workspace }}/.local/bin:/usr/local/bin:/usr/bin:/bin
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: stable

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install uv and setup Python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Format check
        run: uv run --directory python ruff format --check .

      - name: Lint with ruff
        run: uv run --directory python ruff check --select I .

      - name: Static type check
        run: uv run --directory python mypy .

      - name: Check licenses
        run: ./scripts/check_license

      - name: Build Rust extension for Python ${{ matrix.python-version }}
        working-directory: ./python
        run: |
          uv venv --python python${{ matrix.python-version }}
          uv run --active --directory handlebarrz maturin develop

      - name: Run Python tests for Python ${{ matrix.python-version }}
        working-directory: ./python
        run: |
          uv run --active pytest -xvvs --log-level=DEBUG .

      - name: Run Rust tests for handlebarrz
        run: ./scripts/run_rust_tests

      - name: Install d2lang diagramming tool
        run: go install oss.terrastruct.com/d2@latest

      - name: Install mkdocs
        run: |
          uv tool install \
          mkdocs \
          --with mkdocs-autorefs \
          --with mkdocs-d2-plugin \
          --with mkdocs-literate-nav \
          --with mkdocs-material \
          --with mkdocs-mermaid2-plugin \
          --with mkdocs-minify-plugin \
          --with mkdocstrings[python]

      - name: Build documentation
        run: uv run mkdocs build --strict

      - name: Build distributions
        run: ./scripts/build_dists
