# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Python Checks

on: pull_request

jobs:
  python-checks:
    runs-on: ubuntu-latest
    env:
      PATH: ${{ github.workspace }}/go/bin:${{ github.workspace }}/.cargo/bin:${{ github.workspace }}/.local/share/pnpm:${{ github.workspace }}/.local/bin:/usr/local/bin:/usr/bin:/bin
    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Pre-requisites
        run: scripts/setup -a ci

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install uv and setup Python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Format check
        run: uv run --directory python ruff format --check .

      - name: Lint with ruff
        run: uv run --directory python ruff check --select I .

      - name: Static type check
        run: uv run --directory python mypy .

      - name: Check licenses
        run: ./scripts/check_license

      - name: Run Python tests
        run: ./scripts/run_python_tests

      - name: Run Rust tests for handlebarrz
        run: ./scripts/run_rust_tests

      - name: Build documentation
        run: uv run mkdocs build --strict

      - name: Build distributions
        run: ./scripts/build_dists
