# Copyright 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Release JS

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: Release tag
        type: choice
        default: next
        required: true
        options:
          - next
          - latest

jobs:
  build:
    name: Run build tasks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v3
    - name: Set up node v21
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'pnpm'
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Install dependencies
      working-directory: ./js
      run: pnpm install
    - name: Run build script
      working-directory: ./js
      run: pnpm build
    - name: Run js tests
      working-directory: ./js
      run: pnpm test
    - name: Set up node v21
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'pnpm'
        registry-url: 'https://wombat-dressing-room.appspot.com/'
    - name: release script
      shell: bash
      run: RELEASE_BRANCH=${{ steps.extract_branch.outputs.branch }} RELEASE_TAG=${{ inputs.releaseTag }} .github/scripts/release.sh
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
