# Copyright 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: "JS: Run Tests"

on:
  push:
    paths:
      - "js/**"
      - "spec/**"
  pull_request:
    paths:
      - "js/**"
      - "spec/**"

jobs:
  test:
    name: Run tests (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20', '21', '22', '23']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: cd js && pnpm install

      - name: Run tests
        run: cd js && pnpm test
